Add metric response helper function
projectdiscovery/clistats pull request #32
Opened 2023-05-02 16:54 UTC by RamanaReddy0M

2023-05-05 10:31 UTC, tarunKoyalwar requested changes

2023-05-05 10:31 UTC, tarunKoyalwar commented on clistats.go
> +	return statString
@RamanaReddy0M suggesting a minor refactor.  in cases if there is a network error (say /metrics enpoints is not available i.e .Start() was not called or something else). using `GetStatResponse()` will just spam cli and will not exit .

I think we can change this behaviour to stop/close channel if there is a error

2023-05-08 21:14 UTC, tarunKoyalwar approved these changes
lgtm !

2023-05-15 13:00 UTC, Mzack9999 requested changes
suggesting alternative callback implementation and requesting changes to discuss

2023-05-15 15:24 UTC, RamanaReddy0M commented on clistats.go
> +func (s *Statistics) GetStatResponse(interval time.Duration) <-chan string {
@Mzack9999 This implementation looks clean. With this change, we can remove the dependency on `gologger` and no longer need to call this method inside a goroutine.

2023-05-15 16:52 UTC, tarunKoyalwar commented on clistats.go
> +func (s *Statistics) GetStatResponse(interval time.Duration) <-chan string {
@Mzack9999 , @RamanaReddy0M this is great . but if possible i think we can add a default callback function in same file
Ex:
```
var DefaultResponseCallback = func(s string,err error) {}
```
because this function fetches stats from localhost:[someport] so there shouldn't be a network error . and if there is a error it most likely is a fatal error <- this was my original intention behind exiting on err

2023-05-16 16:26 UTC, Mzack9999 requested changes
I think the implementation is good, but noticed now that probably we are leaking a ticker, so I think we would need a break mechanism, just throwing here an idea (code probably won't compile):
```go
...
func (s *Statistics) GetStatResponse(interval time.Duration, callback func(string, error) error) {
...
go func() {
	for range ticker.C {
		if err := callback(metricCallback(url)); err != nil {
			ticker.Stop()
			return
		}
	}
}()
```
Do you think we can use the callback error as break out condition?

2023-05-18 05:40 UTC, Mzack9999 approved these changes

2023-05-18 05:41 UTC, merged